apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: helm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube 
    spec:
      containers:
      - name: sonarqube 
        image: petergillhmg/sonarqube:1
        resources:
          requests: 
            memory: "128Mi"
            cpu: "256m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000

---

apiVersion: v1
kind: Service 
metadata: 
  name: sonarqubesvc
  namespace: helm-deployment
spec: 
  type: LoadBalancer
  selector: 
    app: sonarqube
  ports: 
    - port: 80
      targetPort: 9000
